import Navbar from "../components/Navbar";
import Footer from "../components/footer";

export const SecurityPage = ()=>{

    return(<>
        <Navbar/>
        <section className="py-10">
            <div className="container mx-auto mt-5 px-7 py-10 h-screen bg-[url('./bg-aboutus.jpeg')] bg-cover p-6 [&>h5]:text-secondary-color [&>h5]:font-semibold">
                <h2 className="font-body-font text-secondary-color font-bold text-2xl lg:text-4xl my-3">Secure & Convenient Form Access</h2>
                <p className="text-secondary-light leading-5 mb-5"><span className="font-semibold"> Your Data, Your Control — Anytime, Anywhere </span><br />
                    At FormMeUp, we believe that seamless access should never come at the cost of security. That's why we've built our platform around robust, enterprise-grade security protocols that protect both form creators and form respondents at every stage of the process.</p>
                <h5>Secure, Password-Protected Links</h5>
                <p className="text-secondary-light leading-5 mb-3">Each form generated by FormMeUp is delivered via a unique, encrypted URL. For added protection, forms are accessible only through a password that can be delivered securely via your chosen communication method (e.g., email or Whatsup ....). This ensures that only intended recipients can access and interact with the form, eliminating the risks associated with open or publicly shared forms.</p>
                <h5>Instant, Secure Access</h5>
                <p className="text-secondary-light leading-5 mb-3">There’s no need for users to create accounts or download software. Once they receive the link and password, they can immediately fill out the form through a responsive, mobile-friendly interface. After completing the form, they can instantly download a professionally formatted PDF version — all while staying within our secure environment.</p>
                <h5>End-to-End Data Protection</h5>
                <p className="text-secondary-light leading-5 mb-3">We use SSL encryption across all data transmissions, so your information remains protected during every interaction. From the moment a form is generated to the final PDF download, all data is handled with strict privacy safeguards. We also utilize secure backend storage and follow best practices for data retention, access control, and audit logging.</p>
                <h5>Transparency & Trust</h5>
                <p className="text-secondary-light leading-5 mb-5">We know that when it comes to forms — especially those collecting sensitive or personal information — trust is everything. That’s why we’ve built FormMeUp to be as transparent and reliable as possible. We never sell or share your data, and access to stored form data is limited to only those with verified credentials.</p>
                <h5>Why It Matters</h5>
                <p className="text-secondary-light leading-5">Whether you're collecting legal documents, onboarding information, health records, or customer feedback, data privacy is non-negotiable. With FormMeUp, you’re not just sending forms — you’re sending them with peace of mind.</p>
            </div>
        </section>
        <Footer/>
    </>);
}